routes/web.php
    Route::get('user/{id}', 'UserController@status');
     // Kpis
     Route::resource('kpis', KpiController::class);
     // End Kpis

     Route::get('kpi_evaluation_form',[KpiEvalationFormController::class,'index']);


    // Calculation Groups
    Route::resource('calculationGroups' , CalculationGroupController::class);
    // Company Belongnings
    Route::resource('company_belongings' , CompanyBelongingsController::class);
    Route::resource('issue_belonging' , IssueBelongingsController::class);
    Route::post('returning_belonging/{id}' , 'IssueBelongingsController@returning_belonging');
    // Route::post('return_belonging/{id}' , 'IssueBelongingsController@return_belonging');

    // Payment Codes
    Route::resource('paymentCodes' , PaymentCodesController::class);
    // Employee Payments
    Route::resource('employeePayments' , EmployeePaymentsController::class);
    // Medical Claims
    Route::resource('medicalClaims' , MedicalClaimsController::class);
    // Payroll Processing
    Route::post('payrollProcessing/{id}' , 'PayrollProcessingController@processPayroll');
    Route::get('downloadMultiple' , 'PayrollProcessingController@downloadMultiple');
    Route::post('check-payroll-accrual-jv' , 'PayrollProcessingController@checkPayrollAccrualJV');
    Route::post('payrollAccrualJV' , 'PayrollProcessingController@PayrollAccrualJV');
    Route::delete('delete-payroll-accrual-jv/{payroll}' , 'PayrollProcessingController@deletePayrollAccrualJV');
    Route::get('payroll-accrual-payment' , 'PayrollProcessingController@PayrollAccrualPayment');
    Route::post('payroll-accrual-payment' , 'PayrollProcessingController@storePayrollAccrualPayment');
    Route::get('view-accrual-voucher/{voucher_no}' , 'PayrollProcessingController@accrualPaymentVoucherView')->name('view-accrual-voucher');
    Route::get('accrual-payment-vouchers' , 'PayrollProcessingController@accrualPaymentVouchers');
    Route::post('accrual-payment-voucher' , 'PayrollProcessingController@sendAccrualPaymentVoucher');
    Route::resource('payrollProcessing' , PayrollProcessingController::class);
    Route::get('get-payrolls-erpurls' , 'PayrollProcessingController@payrollsErpUrls');
    Route::post('payrolls-erpurls' , 'PayrollProcessingController@storePayrollsErpUrls');
    Route::get('payroll-employee-columns/{payroll}' , 'PayrollProcessingController@payrollEmployeeColumns');
    Route::post('payroll-employee-columns/{payroll}' , 'PayrollProcessingController@storePayrollEmployeeColumns');
    // Calculation Methods
    Route::resource('calculationMethods' , CalculationMethodsController::class);
    // Overtime Administration
    Route::resource('overtimeAdministration' , OvertimeAdministrationController::class);
    // Job Details Setup
    Route::resource('jobDetailsSetup' , JobDetailsSetupController::class);
    // Data Import
    Route::resource('dataImport' , DataImportController::class);
    // Manage Metadata
    Route::resource('manageMetadata' , ManageMetadataController::class);
    // HR Form Management
    Route::resource('hrFormManagement' , HRFormManagementController::class);
    // Company Payroll
    Route::resource('companyPayroll' , CompanyPayrollController::class);
    // Employee Training Sessions
    Route::resource('employeeTrainingSessions' , EmployeeTrainingSessionController::class);
    // Payroll Columns
    Route::resource('payrollColumns' , PayrollColumnsController::class);
    // Attendance Dashboard
    Route::resource('attendance_dashboard' , AttendanceDashboardController::class);
    // Manual Attendance
    Route::resource('manualAttendance' , ManualAttendanceController::class);
    // Monthly KPI Report
    Route::resource('monthlyKPIReport' , MonthlyKPIController::class);
    // Yearly KPI Report
    Route::resource('yearlyKPIReport' , YearlyKPIController::class);
    // Company Loans
    Route::resource('companyLoans' , CompanyLoansController::class);
    // Loans
    Route::resource('loans' , LoanController::class);
    // Asset Issuance
    Route::resource('assetIssuance' , AssetIssuanceController::class);
    // Entitlement
    Route::resource('entitlement' , EntitlementController::class);
    // Entitlement Assignment
    Route::resource('entitlementAssignment' , EntitlementAssignmentController::class);
    // Key Performance Indicator
    Route::resource('performanceIndicator' , PerformanceIndicatorController::class);
    // Insurance Types
    Route::resource('insuranceTypes' , InsuranceTypeController::class);
    // Insurance Sub Types
    Route::resource('insuranceSubTypes' , InsuranceSubTypeController::class);
    // Salary Slip
    Route::resource('salary_slip' , SalarySlipController::class);
    // Staff Directory
    Route::resource('staff_directory' , StaffDirectoryController::class);
    Route::get('attachment_download/{id}' , 'StaffDirectoryController@attachment_download');
    // Insurance Allocation
    Route::resource('insuranceAllocation' , InsuranceAllocationController::class);
    // Payroll History
    // Route::resource('payrollHistory' , PayrollHistoryController::class);
    // Employee Disciplinary Action
    Route::resource('employee_disciplinary_action' , EmployeeDisciplinaryActionController::class);
    // Job Positions
    Route::resource('job_positions' , JobPositionsController::class);
    // Company Banks
    Route::resource('company_banks' , CompanyBanksController::class);
    // Bulk Shift Management
    Route::resource('bulk_shift_management', BulkShiftController::class);
    // Bulk Time In
    Route::resource('bulk_time_in_department', BulkTimeInDepartmentController::class);
    // Bulk Bulk Attendance Job
    Route::resource('bulk_attendance_job_wise', BulkAttendanceJobController::class);
    // Bulk Time In Employee Controller
    Route::resource('bulk_time_in_employee', BulkTimeInEmployeeController::class);
    // Bulk Time Out
    Route::resource('bulk_time_out', bulkTimeOutController::class);
    Route::resource('bulk_time_out_jsml', bulkTimeOutJsmlController::class);
    // Report Columns
    Route::resource('report_columns', ReportColumnsController::class);
    // Overtime Hourly Pay And Net Salary Column
    Route::resource('overtime_hourly_paycolumn', OvertimeHourlyAndNetSalaryColumnController::class);
    // Consolidated Bank Sheet
    Route::resource('consolidated_bank_sheet', ConsolidatedSheetController::class);
    // Fuel Rate
    Route::resource('fuel_rate', FuelRateController::class);
    // Department Wise Salary Summary
    Route::resource('department_wise_salary', DepartmentWiseSalaryController::class);
    // Salary Componenet History
    Route::resource('salary_comp_history', SalaryComponentHistoryController::class);
    // Payroll Bulk Edit
    Route::resource('payroll_bulk_edit', PayrollBulkEditController::class);
    // Salary Plan
    Route::resource('salary_plan', SalaryPlanController::class);
    // Tax Report
    Route::resource('tax_report', TaxReportController::class);
    // Employee History
    Route::resource('employee_history', EmployeeHistoryController::class);
    Route::get('single_employee_history', 'EmployeeHistoryController@single_employee_history');
    // Attendance Report
    Route::resource('attendance_report', AttendanceReportController::class);
    Route::get('absentessReport', 'AttendanceReportController@index');
    Route::get('missing_checkout_report', 'AttendanceReportController@index');
    // Attendance History
    Route::get('attendance_history', 'AttendanceReportController@index');
    // Attendance Approval Controller
    Route::resource('attendance_approval', AttendanceApprovalController::class);
    // JSML Salary Slip
    // Route::resource('jsml_salary_slip', JSMLSalarySlipController::class);
    // PaySlip Templates
    Route::resource('payslip_template', PayslipTemplateController::class);
    Route::post('payslip_template/{id}' , 'PayslipTemplateController@update');

    // Miscellaneous Request Type
    Route::resource('MiscellaneousRequestType', MiscellaneousRequestTypeController::class);
    Route::resource('fineReversal', FineReversalRequestController::class);

    // Reports
    Route::get('bank_salary_sheet', 'ReportController@bank_salary_sheet');
    Route::get('time_conflict_report', 'ReportController@time_conflict_report');
    Route::get('login-report', 'ReportController@LoginReport');
    Route::get('gross_salary_report', 'ReportController@gross_salary_report');
    Route::get('bank_salary_report', 'ReportController@bank_salary_report');
    Route::get('departmentWiseSalary', 'ReportController@departmentWiseSalary');
    Route::get('designationWiseSalary', 'ReportController@designationWiseSalary');
    Route::get('salaryHistory', 'ReportController@salaryHistory');
    Route::get('departmentWiseSalarySummery', 'ReportController@departmentWiseSalarySummery');
    Route::get('eobiMonthlyReport', 'ReportController@eobiMonthlyReport');
    Route::get('uifMonthlyReport', 'ReportController@uifMonthlyReport');
    Route::get('uifReport', 'ReportController@uifReport');
    Route::get('UIFFile', 'ReportController@UIFFile');
    Route::get('IRP5Report', 'ReportController@IRP5Report');
    Route::get('EMP501 Report', 'ReportController@EMP501 Report');
    Route::get('EMP501 ETI Breakdown Report', 'ReportController@EMP501 ETI Breakdown Report');
    Route::get('EMP201 Breakdown Report', 'ReportController@EMP201 Breakdown Report');
    Route::get('EMP201', 'ReportController@EMP201');
    Route::get('EEA2 Report', 'ReportController@EEA2 Report');
    Route::get('EEA2 Detail Report', 'ReportController@EEA2 Detail Report');
    Route::get('EEA4Report', 'ReportController@EEA4Report');
    Route::get('EEA4DetailReport', 'ReportController@EEA4DetailReport');
    Route::get('DirectiveNumberReport', 'ReportController@DirectiveNumberReport');
    Route::get('COIDAReport', 'ReportController@COIDAReport');
    Route::get('COIDABreakdownReport', 'ReportController@COIDABreakdownReport');

app/Models/PayrollColumn.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class PayrollColumn extends Model implements Auditable
{
    use HasFactory,  \OwenIt\Auditing\Auditable;
    protected $table = 'payrollcolumns';
    protected $guarded = [];
}

app/Http/Controllers/FinanceController.php
<?php

namespace App\Http\Controllers;
use DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class FinanceController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    public function index(Request $request) 
    {
        $departments = DB::table('companystructures')->get();
        $employees = DB::table('employees')->get();
        $payFrequency = DB::table('payfrequency')->get();
        $currency = DB::table('currencytypes')->get();
        $calculationGroup = DB::table('deductiongroup')->get();
        $calculation_Exemptions_Assigned = DB::table('deductions')->get(); 
        return view('Admin.finance.salarysetup.index', compact('departments','employees','payFrequency','currency','calculationGroup','calculation_Exemptions_Assigned')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Admin/finance/payrollColumns/index.blade.php
@extends('Admin.layouts.master')
@section('title', 'Payroll Columns')

@section('content')
    <section class="content-wrapper container-xxl p-0">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Payroll Columns</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Finance</a>
                                </li>
                                <li class="breadcrumb-item active">Payroll Columns
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <section id="basic-datatable">
                <div class="row">
                    <div class="col-12">
                        <div class="card pb-2">
                            <table class="table" id="dataTable">
                                <thead>
                                    <tr>
                                        <th class="not_include"></th>
                                        <th>Sr.No</th>
                                        <th>Name</th>
                                        <th>Column Order</th>
                                        <th>Salary Components</th>
                                        <th>Calculation Method</th>
                                        <th>Calculation Group</th>
                                        <th class="not_include">Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </section>

@endsection
@section('scripts')
    @if(Session('success_message'))
        <script>
            Toast.fire({
                icon: "success",
                title: "{!! Session('success_message') !!}"
            })
        </script>
    @endif
    <script>
        var rowid;
        $(document).ready(function() {
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: {
                    url: "{{ route('payrollColumns.index') }}",
                },
                columns: [{
                        data: 'responsive_id'
                    },
                    {
                        data : 'DT_RowIndex',
                        name : 'DT_RowIndex', 
                        searchable: false
                    },
                    {
                        data: 'payroll_column',
                        name: 'payrollcolumns.name',
                    },
                    {
                        data: 'colorder',
                        name: 'payrollcolumns.colorder',
                    },
                    {
                        data: 'salary_comp',
                        name: 'salarycomponent.name',
                    },
                    {
                        data: 'cal_method',
                        name: 'deductions.name',
                    },
                    {
                        data: 'cal_group',
                        name: 'deductiongroup.name',
                    },
                    {
                        data: '',
                    },
                ],
                "columnDefs": [{
                        // For Responsive
                        className: 'control',
                        orderable: false,
                        searchable: false,
                        targets: 0
                    },
                    {
                        // Actions
                        targets: -1,
                        orderable: false,
                        searchable: false,
                        title: 'Actions',
                        render: function(data, type, full, meta) {
                            return (
                                '<a href="{{url("payrollColumns/")}}'+"/"+full.id+'/edit" class="item-edit">' +
                                feather.icons['edit'].toSvg({
                                    class: 'font-medium-4'
                                }) +
                                '</a>'
                                // '<a href="javascript:;" onclick="delete_item(' + full.id +
                                // ')">' +
                                // feather.icons['trash-2'].toSvg({
                                //     class: 'font-medium-4 text-danger'
                                // }) +
                                // '</a>'
                            );
                        }
                    },
                    {
                        "defaultContent": "-",
                        "targets": "_all"
                    }
                ],
                dom: '<"card-header border-bottom p-1"<"head-label"><"dt-action-buttons text-end"B>><"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
                displayLength: 10,
                aLengthMenu: [
                    [10,25,50,100,-1],
                    [10,25,50,100,"All"]
                ],
                buttons: [{
                        extend: 'collection',
                        className: 'btn btn-outline-secondary dropdown-toggle me-2',
                        text: feather.icons['share'].toSvg({
                            class: 'font-small-4 me-50'
                        }) + 'Export',
                        buttons: [{
                                extend: 'print',
                                text: feather.icons['printer'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Print',
                                className: 'dropdown-item',
                                title: 'Payroll Columns',
                                action: newexportaction,
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'csv',
                                text: feather.icons['file-text'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Csv',
                                className: 'dropdown-item',
                                title: 'Payroll Columns',
                                action: newexportaction,
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'excel',
                                text: feather.icons['file'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Excel',
                                className: 'dropdown-item',
                                title: 'Payroll Columns',
                                action: newexportaction,
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'pdf',
                                text: feather.icons['clipboard'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Pdf',
                                className: 'dropdown-item',
                                title: 'Payroll Columns',
                                orientation: 'landscape',
                                pageSize: 'LEGAL',
                                action: newexportaction,
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'copy',
                                text: feather.icons['copy'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Copy',
                                className: 'dropdown-item',
                                title: 'Payroll Columns',
                                action: newexportaction,
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            }
                        ],
                        init: function(api, node, config) {
                            $(node).removeClass('btn-secondary');
                            $(node).parent().removeClass('btn-group');
                            setTimeout(function() {
                                $(node).closest('.dt-buttons').removeClass('btn-group')
                                    .addClass('d-inline-flex');
                            }, 50);
                        }
                    },
                    {
                        text: feather.icons['plus'].toSvg({
                            class: 'me-50 font-small-4'
                        }) + 'Add New',
                        className: 'create-new btn btn-primary',
                        action: function (e, dt, node, config)
                        {
                            window.location.href = '{{route("payrollColumns.create")}}';
                        }
                    }
                ],
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.childRowImmediate,
                        type: 'column',
                    }
                },
                language: {
                    paginate: {
                        // remove previous & next text from pagination
                        previous: '&nbsp;',
                        next: '&nbsp;'
                    }
                }
            });
            $('div.head-label').html('<h6 class="mb-0">List of Payroll Columns</h6>');
        });

        function delete_item(id) {
            $.confirm({
                icon: 'far fa-question-circle',
                title: 'Confirm!',
                content: 'Are you sure want to delete!',
                type: 'orange',
                typeAnimated: true,
                buttons: {
                    Confirm: {
                        text: 'Confirm',
                        btnClass: 'btn-orange',
                        action: function() {
                            $.ajax({
                                url: "payrollColumns/" + id,
                                type: "DELETE",
                                data: {
                                    _token: "{{ csrf_token() }}",
                                },
                                success: function(response) {
                                    if (response.error_message) {
                                        Toast.fire({
                                            icon: 'error',
                                            title: 'An error has been occured! Please Contact Administrator.'
                                        })
                                    } else if (response.code == 300) {
                                        $.alert({
                                            icon: 'far fa-times-circle',
                                            title: 'Oops!',
                                            content: response.message,
                                            type: 'red',
                                            buttons: {
                                                Okay: {
                                                    text: 'Okay',
                                                    btnClass: 'btn-red',
                                                }
                                            }
                                        });
                                    } else {
                                        $('#dataTable').DataTable().ajax.reload();
                                        Toast.fire({
                                            icon: 'success',
                                            title: 'Company Payroll has been Deleted Successfully!'
                                        })
                                    }
                                }
                            });
                        }
                    },
                    cancel: function() {
                        $.alert('Canceled!');
                    },
                }
            });
        }
    </script>
@endsection